### PR TITLE
Supported the new Android plugins APIs

### PR DESCRIPTION
**Pull request by miyakeryo**
[Supporting the new Android plugins APIs - Flutter](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration)

### CODE REVIEW

**Comment by operando** [comment]
Thanks 👍 
I'm reviewing it, so please wait a while.

**Comment by higorlapacw** [comment]
Any news on this?

**Comment by operando** [comment]
LTGM 👍
Thanks🎉

**Comment by dodatw** [comment]
I tried the last code. it still have error:
e: /Users/rdapp/.pub-cache/git/advertising_id-2f717d7597105b6150d46dcf2ea81df5cd757dc3/android/src/main/kotlin/com/os/operando/advertisingid/AdvertisingIdPlugin.kt: (16, 7): Redeclaration: AdvertisingIdPlugin
e: /Users/rdapp/.pub-cache/hosted/pub.dartlang.org/advertising_id-1.1.0/android/src/main/kotlin/com/os/operando/advertisingid/AdvertisingIdPlugin.kt: (17, 7): Redeclaration: AdvertisingIdPlugin
e: /Users/rdapp/.pub-cache/hosted/pub.dartlang.org/advertising_id-1.1.0/android/src/main/kotlin/com/os/operando/advertisingid/AdvertisingIdPlugin.kt: (22, 48): Too many arguments for public constructor AdvertisingIdPlugin() defined in com.os.operando.advertisingid.AdvertisingIdPlugin
e: /Users/rdapp/.pub-cache/hosted/pub.dartlang.org/advertising_id-1.1.0/android/src/main/kotlin/com/os/operando/advertisingid/AdvertisingIdPlugin.kt: (23, 41): Type mismatch: inferred type is BinaryMessenger! but FlutterPlugin.FlutterPluginBinding was expected

**Pull request merged**
